version: '3.7'
services:
  budget-app-api:
    container_name: budget-app-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 5000:5000     

